FROM alpine:3.17

RUN apk update && apk add bash

WORKDIR /tmp

RUN wget https://nodejs.org/dist/v18.12.1/node-v18.12.1-linux-x64.tar.xz
RUN tar -xf node-v18.12.1-linux-x64.tar.xz --directory=/usr/local --strip-components=1
RUN rm node-v18.12.1-linux-x64.tar.xz

RUN apk add npm

SHELL [ "/bin/bash", "-c" ]

WORKDIR /xui/common

COPY .storybook .storybook
COPY public public
COPY scripts scripts
COPY src src
COPY eslintrc.cjs eslintrc.cjs
COPY .gitignore .gitignore
COPY LICENSE LICENSE
COPY README.md README.md
COPY index.html index.html
COPY package-lock.json package-lock.json
COPY package.json package.json
COPY vite.config.js vite.config.js
COPY yarn.lock yarn.lock


# Install dependencies
RUN npm install

# Build Storybook
RUN npm run build-storybook

# Install http-server to serve the static files
RUN npm install -g http-server


CMD ["tail", "-f", "/dev/null"]

# Expose the port
EXPOSE 6006
